spring:
  application:
    name: shorted-url
  datasource:
    url: jdbc:mysql://{url banco}/shorted
    password: {password}
    username: {user}
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect:  org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      show-sql: true
